import os

DB_URL = os.environ["DB_URL"]

DB_SCHEMA = os.environ["DB_SCHEMA"]


SPIDER_RUN_TASK_EXECUTION_ADVANCE_TIME = int(
    os.getenv("SPIDER_RUN_TASK_EXECUTION_ADVANCE_TIME", 300)
)

SPIDER_RUN_TASK_EXECUTION_DEADLINE_TIME = int(
    os.getenv("SPIDER_RUN_TASK_EXECUTION_DEADLINE_TIME", 3600)
)
