version: "3.9"

services:
  db:
    image: postgres:14
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: omnibus
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    command:
      - postgres
      - -c
      - shared_buffers=256MB
      - -c
      - work_mem=32MB
      - -c
      - maintenance_work_mem=128MB

  db-isready:
    image: alpine:latest
    depends_on:
      db:
        condition: service_healthy
