name: "Deploy Container Image"

on:
  push:
    branches:
      - main
jobs:
  deploy-container-image:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3

      - uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/930603913796/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "github-actions@logos-369708.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - run: gcloud auth configure-docker

      - name: Build Docker Image
        run: docker build -t asia.gcr.io/logos-369708/spinner-scheduler:latest .

      - name: Push Docker Image
        run: docker push asia.gcr.io/logos-369708/spinner-scheduler:latest

      - name: "Deploy to Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v0"
        with:
          image: asia.gcr.io/logos-369708/spinner-scheduler:latest
          service: "spinner-scheduler"
          region: "asia-northeast1"
