name: Cubic API deploy

on:
  workflow_call:
    inputs:
      cloud-run-concurrency:
        default: 16
        required: false
        type: number
      cloud-run-cpu:
        default: 1
        required: false
        type: number
      cloud-run-max-instance:
        default: 2
        required: false
        type: number
      cloud-run-memory:
        default: 2Gi
        required: false
        type: string
      cloud-run-min-instance:
        default: 0
        required: false
        type: number
      cloud-run-port:
        default: 8080
        required: false
        type: number
      cloud-run-region:
        default: asia-northeast1
        required: false
        type: string
      cloud-run-sa:
        required: true
        type: string
      cloud-run-service-name:
        default: spindle-invoker
        required: false
        type: string
      cloud-run-timeout:
        default: 360s
        required: false
        type: string
      cloud-sql-connection-name:
        required: true
        type: string
      docker-image-base-url:
        required: true
        type: string
      gar-hostname:
        default: asia-northeast1-docker.pkg.dev
        required: true
        type: string
      gcp-project-id:
        required: true
        type: string
      gcp-wi-provider:
        required: true
        type: string
      gcp-wi-sa:
        required: true
        type: string
      workflow-region:
        required: true
        type: string
      workflow-name:
        required: true
        type: string

jobs:
  deploy-spindle-invoker:
    name: Deploy spindle invoker

    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_HASHED_TAG: ${{ inputs.docker-image-base-url }}:${{ github.sha }}
      DOCKER_IMAGE_LATEST_TAG: ${{ inputs.docker-image-base-url }}:latest

    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ inputs.gcp-wi-provider }}
          service_account: ${{ inputs.gcp-wi-sa }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Auth Artifact Registry
        run: gcloud auth configure-docker ${{ inputs.gar-hostname }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: "v0.10.5"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src/spindle_invoker
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_HASHED_TAG }}
            ${{ env.DOCKER_IMAGE_LATEST_TAG }}
          provenance: false
          cache-from: "type=gha"
          cache-to: "type=gha,mode=max"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ inputs.cloud-run-service-name }} \
          --image=${{ env.DOCKER_IMAGE_HASHED_TAG }} \
          --project=${{ inputs.gcp-project-id }} \
          --region=${{ inputs.cloud-run-region }} \
          --service-account=${{ inputs.cloud-run-sa }} \
          --concurrency=${{ inputs.cloud-run-concurrency }} \
          --cpu=${{ inputs.cloud-run-cpu }} \
          --ingress=all \
          --max-instances=${{ inputs.cloud-run-max-instance }} \
          --memory=${{ inputs.cloud-run-memory }} \
          --min-instances=${{ inputs.cloud-run-min-instance }} \
          --port=${{ inputs.cloud-run-port }} \
          --timeout=${{ inputs.cloud-run-timeout }} \
          --set-secrets="DATABASE_URL=conn-string-spindle-scheduler:latest" \
          --set-env-vars="WORKFLOW_PROJECT_ID=${{ inputs.gcp-project-id }}" \
          --set-env-vars="WORKFLOW_LOCATION=${{ inputs.workflow-region }}" \
          --set-env-vars="WORKFLOW_NAME=${{ inputs.workflow-name }}" \
          --no-allow-unauthenticated \
          --add-cloudsql-instances=${{ inputs.cloud-sql-connection-name }}
